# Generated by Django 4.1 on 2024-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loandetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(max_length=254)),
                ('time', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=254)),
                ('term', models.CharField(max_length=254)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
